name: Pipeline-CI
on:
    push:
        branches: [ master ]
jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: docker://yoanbernabeu/phpqa-with-tools
            - name: Composer Install
              run: composer install