name: Pipeline-CI
on:
    push:
        branches: [ master ]
jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/shivammathur
            - name: LS
                run: ls 
