name: Pipeline-CI
on:
    push:
        branches: [ master ]
jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: docker://jakzal/phpqa
            - name: LS
              run: ls